channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - hvplot
  - datashader
  - pandas
  - bokeh
  - xarray
  - dask
  - distributed
  - intake
  - intake-esm
  - intake-xarray
  - xesmf
  - pydap
  - climpred
  - eofs
  - regionmask
  - xgcm
  - xhistogram
  - seaborn
  - cartopy
  - rise
  - pip:
    - jupyter-contrib-nbextensions

